### ISSUE TITLE
Setpoint error

### ISSUE THREAD

**Issue by EnserNG** [Numynum/BlizzMovePlugin_QuestTracker#1] opened 2021-04-26 18:15 UTC
Thanks so much for adding the functionality - the tracker has been just slightly in the way for a long while.  
So... you can move and resize perfectly but then getting the following error popping up quite a bit per session:
Message: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: ObjectiveTrackerFrame:SetPoint.
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: SetPoint()
   [string "@..\FrameXML\UIParent.lua"]:3416: UIParentManageFramePositions()
   [string "@..\FrameXML\UIParent.lua"]:2637:
      ..\FrameXML\UIParent.lua:2624
   [string "=[C]"]: SetAttribute()
   [string "@..\FrameXML\UIParent.lua"]:3427:
      ..\FrameXML\UIParent.lua:3425
   [string "=[C]"]: UIParent_ManageFramePositions()
   [string "@Blizzard_UIWidgets\Blizzard_UIWidgetBelowMinimapFrame.lua"]:5: layoutFunc()
   [string "@Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:480: UpdateWidgetLayout()
   [string "@Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:456: ProcessAllWidgets()
   [string "@Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:23:
      ...dOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:21
Locals:

**Comment by Numynum** [comment] 2021-04-26 18:41
how have you configured blizzmove? to remember frame positions in-session, permanently, or not at all?

**Comment by Numynum** [comment] 2021-04-26 18:42
generally, if you want to move the quest tracker frame permanently, you might want to use a different addon (like elvui or moveanything)
blizzmove is better for moving things temporarily (to the point, where remembering permanently is an unsupported feature atm)

**Comment by EnserNG** [comment] 2021-04-26 20:11
Have tried with both the per session and permanent options to the same result.
Good point on the permanent move - will give them a look.  Thank you!

**Comment by Numynum** [comment] 2021-04-27 09:43
sadly I don't think there's too much that can be done about this error
blizzmove has had similar errors reported as well, they sometimes where fixed by resetting cvars `/console cvar_default`
I myself have never had this error, so it's hard to say

**Comment by bolte-io** [comment] 2021-06-26 19:10
I have also just had this error.

` Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: ObjectiveTrackerFrame:SetPoint.
[string "=[C]"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@FrameXML\UIParent.lua"]:3416: in function `UIParentManageFramePositions'
[string "@FrameXML\UIParent.lua"]:2637: in function <FrameXML\UIParent.lua:2624>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3427: in function `UIParent_ManageFramePositions'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetBelowMinimapFrame.lua"]:5: in function `layoutFunc'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:480: in function `UpdateWidgetLayout'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:456: in function `ProcessAllWidgets'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:23: in function <...dOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:21>

Locals:
(*temporary) = ObjectiveTrackerFrame {
 0 = <userdata>
 contentsHeight = 0
 SetHeight = <function> defined =[C]:-1
 blockTemplate = "ObjectiveTrackerBlockTemplate"
 fromModuleOffsetY = -10
 HeaderMenu = <unnamed> {
 }
 fromHeaderOffsetY = -10
 frameData = <table> {
 }
 updateReasonEvents = 0
 lineSpacing = 2
 freeLines = <table> {
 }
 freeTimerBars = <table> {
 }
 lineTemplate = "ObjectiveTrackerLineTemplate"
 freeProgressBars = <table> {
 }
 usedTimerBars = <table> {
 }
 isUpdating = false
 hasSkippedBlocks = false
 usedBlocks = <table> {
 }
 oldContentsHeight = 0
 SetPoint = <function> defined =[C]:-1
 lastMapID = 85
 MODULES = <table> {
 }
 blockType = "Frame"
 blockOffset = <table> {
 }
 BlockDropDown = ObjectiveTrackerBlockDropDown {
 }
 isUpdateDirty = false
 initialized = true
 SetWidth = <function> defined =[C]:-1
 friendlyName = "DEFAULT_OBJECTIVE_TRACKER_MODULE"
 contentsAnimHeight = 0
 lineWidth = 0
 watchMoneyReasons = 0
 poolCollection = <table> {
 }
 BlocksFrame = ObjectiveTrackerBlocksFrame {
 }
 MODULES_UI_ORDER = <table> {
 }
 usedProgressBars = <table> {
 }
 updateReasonModule = 0
}
(*temporary) = "BOTTOMRIGHT"
(*temporary) = "UIParent"
(*temporary) = "BOTTOMRIGHT"
(*temporary) = -12
(*temporary) = 130`

It occurs when I change zone (I am using bugsack, so it alerts me).
It's reproducable by simply exiting Orgrimmar and coming back in (alerts at each zone change).
BlizzMove is set to In session, until you reload.
Latest version of both BlizzMove and this addon.

**Comment by Numynum** [comment] 2021-06-26 21:04
@bolte-io hi, for you the same as I said above, I've never had this issue myself (though I've had similar issues with other addons sometimes)
it's very hard to debug any of these issues, as blizzard sadly doesn't give us any of the tools needed to find out what is actually going wrong here
it's for sure on the things that we're aware of for the main BlizzMove addon, but well.. due to the reasons I've given, it's almost impossible to say for sure why this is going wrong

the only advice I can give, is that sometimes posting `/console cvar_default` in chat has helped people in the past

**Comment by bolte-io** [comment] 2021-06-26 22:40
This issue doesn't occur with the main BlizzMove addon, only with this one.
It's fine though, I'll just use MoveAnything if I need to, or Kaliels Tracker.

**Comment by Numynum** [comment] 2021-06-29 18:40
just as a sidenote/fyi, this addon doesn't really do anything by itself, all the magic is done in the main BlizzMove addon :)
me and the other guys working on the main blizzmove addon have had this exact bug mentioned to us before (usually with the talkinghead frame), so ye, it does happen for some people, but it's almost impossible to reproduce, and thus almost impossible to fix
I would indeed say if your goal is to move the frame permanently, you should be using moveanything or elvui or similar :)

**Comment by Numynum** [comment] 2022-03-27 12:31
this should be fixed when updating to BlizzMove v3.3.0

**Closed as completed by Numynum** 2022-03-27 12:31 UTC
Labels: not-reproduced
